# Generated by Django 2.0 on 2019-11-25 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stu_name', models.CharField(max_length=30, verbose_name='学生名称')),
                ('stu_sex', models.CharField(max_length=5, verbose_name='性别')),
                ('stu_icon', models.IntegerField(max_length=5, verbose_name='年龄')),
                ('stu_describe', models.CharField(max_length=128, verbose_name='介绍')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_name', models.CharField(max_length=30, verbose_name='老师名称')),
                ('t_pwd', models.CharField(max_length=128, verbose_name='密码')),
                ('t_phone', models.CharField(max_length=128, verbose_name='手机号')),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='stu_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.Teacher'),
        ),
    ]
